name: codepipeline-notifier

services:
  localstack:
    container_name: ${COMPOSE_PROJECT_NAME}_localstack
    image: localstack/localstack:3
    ports:
      - 4566:4566 # LocalStack Gateway
      - 4510-4559:4510-4559 # external services port range
    environment:
      DEBUG: ${DEBUG-}
      MAIN_CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}_localstack
      EAGER_SERVICE_LOADING: 1
      SERVICES: 'sts,ssm,cloudformation,iam,s3,ses,sqs,sns,dynamodb,logs,lambda,apigateway,apigatewaymanagementapi,apigatewayv2,cloudfront,route53'
      AWS_DEFAULT_REGION: ${CDK_DEFAULT_REGION:-ap-northeast-1}
      PERSISTENCE: 1
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
